name: CI

on:
  push:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build-test:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Allow git to trust /app
        run: git config --global --add safe.directory /app

      - name: Configure composer authentication
        run: composer config --global github-oauth.github.com ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: Install dependencies
        uses: php-actions/composer@v6

      - name: PHPUnit tests
        run: ./vendor/bin/phpunit
